config/routes.rb
Rails.application.routes.draw do
  # Main routes
  get 'welcome/index'
  root 'welcome#index'

  # Projects / test cases
  resources :projects do
    resources :t_cases, param: :t_case_id, only: :destroy
    resources :t_cases, param: :id, except: :destroy
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
  LEADS = ['pboleguin', 'apaul', 'palan', 'dryan']
  has_many :t_cases, dependent: :destroy
  validates :title, presence: true,
                  length: { minimum: 5 }
  validates :lead, presence: true
end

app/models/t_case.rb
class TCase < ApplicationRecord
  belongs_to :project
  validates :t_case_id, presence: true,
                  length: { minimum: 3 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  skip_before_action :verify_authenticity_token
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  #respond_to :html, :xml, :json
  def index
    @projects = Project.all
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @projects }
      format.json { render :json => @projects }
    end
  end
  def show
    @project = Project.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @project }
      format.json { render :json => @project }
    end
  end
  def new
    @project = Project.new
  end
  def edit
    @project = Project.find(params[:id])
  end
  def create
    @project = Project.new(project_params)
    if @project.save
      respond_to do |format|
        format.html { redirect_to @project}
        format.xml  { render :xml => @project }
        format.json { render :json => @project }
      end
    else
      respond_to do |format|
        format.html { render 'new' }
        format.xml  { render :xml => @project }
        format.json { render :json => @project }
      end
    end
  end
  def update
    @project = Project.find(params[:id])
    if @project.update(project_params)
      redirect_to @project
    else
      render 'edit'
    end
  end
  def destroy
    @project = Project.find(params[:id])
    @project.destroy
    redirect_to projects_path
  end
  private
  def project_params
    params.require(:project).permit(:title, :lead, :description)
  end
end

app/controllers/t_cases_controller.rb
class TCasesController < ApplicationController
  def create
    @project = Project.find(params[:project_id])
    @t_case = @project.t_cases.create(t_case_params)
    redirect_to project_path(@project)
  end
  def destroy
    @project = Project.find(params[:project_id])
    @t_case = @project.t_cases.find_by_t_case_id(params[:t_case_id])
    unless @t_case.present?
      @t_case = @project.t_cases.find(params[:t_case_id])
    end
    @t_case.destroy
    redirect_to project_path(@project)
  end

  private
  def t_case_params
    params.require(:t_case).permit(:t_case_id, :title, :scenario, :status)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/t_cases_helper.rb
module TCasesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TcaseMgt</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/projects/_form.html.erb
<%= form_for @project do |f| %>

  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@project.errors.count, "error") %> prohibited
        this project from being saved:
      </h2>
      <ul>
        <% @project.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.collection_select :lead, Project::LEADS, :to_s, :to_s,
         :include_blank => true
    %>
  </p>
  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>

  <p>
    <%= f.submit %>
  </p>

<% end %>

app/views/projects/edit.html.erb
<h1>Editing project</h1>
<%= render 'form' %>
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<h1>Projects List</h1>
<%= link_to 'New Project', new_project_path %>
<br><br/>
<table>
  <tr>
    <th>Title</th>
    <th>Project Lead</th>
    <th>Description</th>
  </tr>

  <% @projects.each do |project| %>
    <tr>
      <td><%= project.title %></td>
      <td><%= project.lead %></td>
      <td><%= project.description %></td>
      <td><%= link_to 'View', project_path(project) %></td>
      <td><%= link_to 'Update', edit_project_path(project) %></td>
      <td><%= link_to 'Remove', project_path(project),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

app/views/projects/new.html.erb
<h1>New Project</h1>
<%= render 'form' %>
<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @project.title %>
</p>
<p>
  <strong>Project Lead:</strong>
  <%= @project.lead %>
</p>
<p>
  <strong>Description:</strong>
  <%= @project.description %>
</p>
<h2>TCases</h2>

<%= render 't_cases/t_case' %>

<h2>Add a Test Case:</h2>
<%= render 't_cases/form' %>

<%= link_to 'Update', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>

app/views/t_cases/_form.html.erb
<%= form_for([@project, @project.t_cases.build]) do |f| %>
  <p>
    <%= f.label :name, "TCase" %><br>
    <%= f.text_field :t_case_id %>
  </p>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :scenario %><br>
    <%= f.text_area :scenario %>
  </p>
  <p>
    <%= f.label :status %><br>
    <%= f.text_field :status %>
  </p>
  <p>
    <%= f.submit 'Create TCase' %>
  </p>
<% end %>

app/views/t_cases/_t_case.html.erb
<table>
  <tr>
    <th>TCase_id</th>
    <th>Title</th>
    <th>Scenario</th>
    <th>Status</th>
  </tr>
  <% @project.t_cases.each do |t_case| %>
    <tr>
      <td><%= t_case.t_case_id %></td>
      <td><%= t_case.title %></td>
      <td><%= t_case.scenario %></td>
      <td><%= t_case.status %></td>
      <td><%= link_to 'Remove', [t_case.project,  t_case],
                   method: :delete,
                   data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>
<!-- <td><%= link_to 'Remove', [t_case.project,  t_case], -->

app/views/welcome/index.html.erb
<h1>Welcome to TCase_Mgt Home Page</h1>
<p>Your Test Case Management Tool</p>
<%= link_to 'My Projects', controller: 'projects' %>